### ISSUE TITLE
Problems getting the latest D4P W2D plugin to work

### ISSUE THREAD

**Issue by peytonwashere** [dita4publishers/org.dita4publishers.word2dita#9]
Hello,

I was using the DITA4Publishers version 0.9.18 and the Word2DITA plug in was working well. I just updated to the latest version (1.0.0RC14) and integrated it but now the W2D isn't working at all. I'm running it from the command line and it fails each time (even when using the sample .docx provided). I've attached a screen cap of the end where something goes awry. I can also attach a zip of my entire OT folder with plugins installed if that would help. 

I'm running this the same way I was the older version--I drop my .docx into my OT folder, update dita-ot-run-word2dita.xml to point to that file, and then get the new files from the all_defaults/dita folder I have as a folder inside my OT folder. 

![image](https://cloud.githubusercontent.com/assets/12235610/8555207/0fcf94ea-24b4-11e5-9eff-9aa8d5bd1367.png)

I'm not exactly sure what to do at this point and would appreciate any help.

Thanks!
Peyton

**Comment by drmacro** [comment]
Ah, this is a bug that appears when you have the debug parameter turned on (Ant parameter "debug")

I've corrected it in the latest code on the master branch in Git, but the workaround is to not turn debugging on.

**Comment by drmacro** [comment]
Also, you can put the log to a file using the -l {logfilename} Ant parameter. That will make reporting errors easier.

**Comment by peytonwashere** [comment]
Thanks for the quick response! I'm a TOTAL Ant novice, so forgive these dumb questions.
How do I turn debugging off? In dita-ot-run-word2dita.xml, I updated this to be false: <property name="w2d.debug.xslt" value="false"/>, but that gave me the same error.

Also, where do I include that -l command to get the log?

**Comment by drmacro** [comment]
You specify -l on the command line where you use the "ant" command:

````
c:\DITA-OT > ant {stuff} -l word2dita.log
````

There may still be an issue in the current code.

Can you run with the -l flag as shown and provide me the log?

**Comment by peytonwashere** [comment]
Here you go:

, , ,

transformMyDoc:

d4p.wordToDita.init:

wordToDita:
     [echo] [DEBUG] wordToDita.dir=C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita

checkWordDoc:

checkParameters:

initProperties:
     [echo] +++ word2dita-specific properties:
     [echo] #Ant properties
     [echo] #Tue Jul 07 14:49:59 CDT 2015
     [echo] w2d.base.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita
     [echo] w2d.clean.output.dir=true
     [echo] w2d.debug.xslt=false
     [echo] w2d.defaultStyleToTagMap=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita\\xsl\\word-builtin-styles-style2tagmap.xml
     [echo] w2d.generate.navtitles=true
     [echo] w2d.have.word.doc=true
     [echo] w2d.language=en-US
     [echo] w2d.out.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\all_defaults\\dita
     [echo] w2d.root.map.name=word2bookmap_test_01
     [echo] w2d.root.output.filename=word2bookmap_test_01.ditamap
     [echo] w2d.style-to-tag-map=C\:\\DITA-OT\\DITA-OT1.8.5\\style2tagmap.xml
     [echo] w2d.temp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\temp\\temp20150707144959600
     [echo] w2d.topic.extension=.dita
     [echo] w2d.word2dita.xslt=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita\\xsl\\docx2dita.xsl
     [echo] w2p.do.clean.output.dir=true

doWord2Dita:
    [mkdir] Created dir: C:\DITA-OT\DITA-OT1.8.5\temp\temp20150707144959600

unzipWordDoc:
    [unzip] Expanding: C:\DITA-OT\DITA-OT1.8.5\word2bookmap_test_01.docx into C:\DITA-OT\DITA-OT1.8.5\temp\temp20150707144959600\word2bookmap_test_01
     [echo] w2d.style-to-tag-map='C:\DITA-OT\DITA-OT1.8.5\style2tagmap.xml'

cleanOutputDir:
     [echo] [INFO] Cleaning output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...

transformWordToDita:
     [echo] [INFO] Creating output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...
     [echo] [INFO] Creating output file word2bookmap_test_01.ditamap...
     [echo] [INFO] Generating DITA documents from Word document in output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...
     [echo] [INFO]   Using XSLT C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl...
     [xslt] Processing C:\DITA-OT\DITA-OT1.8.5\temp\temp20150707144959600\word2bookmap_test_01\word\document.xml to C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap
     [xslt] Loading stylesheet C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl
     [xslt]  
     [xslt]       ==========================================
     [xslt]       DOCX 2 DITA
     [xslt]       
     [xslt]       Version: ^version^ - build ^buildnumber^ at ^timestamp^
     [xslt]       
     [xslt]       Parameters:
     [xslt]       
     [xslt]       + styleMapUri     = "file:/C:/DITA-OT/DITA-OT1.8.5/style2tagmap.xml"
     [xslt]       + mediaDirUri     = "file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/topics/media"  
     [xslt]       + rootMapName     = "word2bookmap_test_01"
     [xslt]       + rootTopicName   = ""
     [xslt]       + submapNamePrefix= "map"      
     [xslt]       + rootMapUrl      = "word2bookmap_test_01.ditamap"
     [xslt]       + rootTopicUrl    = ""
     [xslt]       + topicExtension  = ".dita"
     [xslt]       + fileNamePrefix  = ""      
     [xslt]       + filterBr        = "false"      
     [xslt]       + filterTabs      = "false"      
     [xslt]       + language        = "en-US"      
     [xslt]       + outputDir       = "file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/"  
     [xslt]       + debug           = "false"
     [xslt]       + includeWordBackPointers= "true"  
     [xslt]       + chartsAsTables  = "false"  
     [xslt]       + saveIntermediateDocs  = "false"  
     [xslt]       
     [xslt]       Global Variables:
     [xslt]       
     [xslt]       + platform         = "windows"
     [xslt]       + debugBoolean     = "false"
     [xslt]       + doSaveIntermediateDocs = "false"
     [xslt]       
     [xslt]       ==========================================
     [xslt]     
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Generating initial simple WP doc....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] wordml2simple: Processing DOCX document.xml file to generate intermediate simpleML XML...
     [xslt]  + [INFO] styleMap=file:/C:/DITA-OT/DITA-OT1.8.5/style2tagmap.xml
     [xslt]  + [INFO] Found 2 font-to-Unicode maps
     [xslt]  + [INFO]   - font2UnicodeMapSymbol.xml
     [xslt]  + [INFO]   - font2UnicodeMapWingdings.xml
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [INFO] wordml2simple: Intermediate simpleML document generated.
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Doing level fixup....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Doing general simpleWpDoc fixup....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Generating DITA result....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ++++++++++++++++++++++++++++++ 
     [xslt]  + [INFO] 
     [xslt]  + [INFO] simple2dita: Processing intermediate simpleML XML to generate DITA XML...
     [xslt]  + [INFO]    
     [xslt]  + [INFO] ++++++++++++++++++++++++++++++
     [xslt]  + [INFO] simple2dita: Phase 1: Generate DITA maps and topics as a single XML document....
     [xslt] C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\simple2dita.xsl:158: Fatal Error! An empty sequence is not allowed as the second argument of relpath:newFile()
     [xslt] Failed to process C:\DITA-OT\DITA-OT1.8.5\temp\temp20150707144959600\word2bookmap_test_01\word\document.xml

BUILD FAILED
C:\DITA-OT\DITA-OT1.8.5\dita-ot-run-word2dita.xml:24: The following error occurred while executing this line:
C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:166: The following error occurred while executing this line:
C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\build-word2dita.xml:210: Fatal error during transformation

Total time: 3 seconds
, , ,

**Comment by drmacro** [comment]
OK, this is a different error now, which is fixed in the latest code.

But it is caused by not setting a value for the rootTopicName XSLT parameter (the bug is not providing an appropriate default in that case).

You can work around this by setting the Ant parameter "w2d.root.topic.name" to whatever you want the root topic name to be.

You can do this in the Ant script using a `<property>` element or on the command line using the -D flag:

````
c:\DITA-OT > ant {stuff} -Dw2d.root.topic.name=root-topic -l mylog.log
````

**Comment by peytonwashere** [comment]
Hmm...I thought I had downloaded the latest version, but I can download it again. Do you know what file in particular is causing the problem so I can just replace that particular one?

I did the work around but still got an error. I'll copy my log below. I'm still using the original style2tagmap.xml and the word2bookmap_test_01.docx that was provided.

```

transformMyDoc:

d4p.wordToDita.init:

wordToDita:
     [echo] [DEBUG] wordToDita.dir=C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita

checkWordDoc:

checkParameters:

initProperties:
     [echo] +++ word2dita-specific properties:
     [echo] #Ant properties
     [echo] #Wed Jul 08 12:09:13 CDT 2015
     [echo] w2d.base.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita
     [echo] w2d.clean.output.dir=true
     [echo] w2d.debug.xslt=false
     [echo] w2d.defaultStyleToTagMap=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita\\xsl\\word-builtin-styles-style2tagmap.xml
     [echo] w2d.generate.navtitles=true
     [echo] w2d.have.word.doc=true
     [echo] w2d.language=en-US
     [echo] w2d.out.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\all_defaults\\dita
     [echo] w2d.root.output.filename=word2bookmap_test_01.ditamap
     [echo] w2d.root.topic.name=root-topic
     [echo] w2d.style-to-tag-map=C\:\\DITA-OT\\DITA-OT1.8.5\\style2tagmap.xml
     [echo] w2d.temp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\temp\\temp20150708120913434
     [echo] w2d.topic.extension=.dita
     [echo] w2d.word2dita.xslt=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita\\xsl\\docx2dita.xsl
     [echo] w2p.do.clean.output.dir=true

doWord2Dita:
    [mkdir] Created dir: C:\DITA-OT\DITA-OT1.8.5\temp\temp20150708120913434

unzipWordDoc:
    [unzip] Expanding: C:\DITA-OT\DITA-OT1.8.5\word2bookmap_test_01.docx into C:\DITA-OT\DITA-OT1.8.5\temp\temp20150708120913434\word2bookmap_test_01
     [echo] w2d.style-to-tag-map='C:\DITA-OT\DITA-OT1.8.5\style2tagmap.xml'

cleanOutputDir:
     [echo] [INFO] Cleaning output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...

transformWordToDita:
     [echo] [INFO] Creating output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...
     [echo] [INFO] Creating output file word2bookmap_test_01.ditamap...
     [echo] [INFO] Generating DITA documents from Word document in output directory C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita...
     [echo] [INFO]   Using XSLT C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl...
     [xslt] Processing C:\DITA-OT\DITA-OT1.8.5\temp\temp20150708120913434\word2bookmap_test_01\word\document.xml to C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap
     [xslt] Loading stylesheet C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita4publishers.word2dita\xsl\docx2dita.xsl
     [xslt]  
     [xslt]       ==========================================
     [xslt]       DOCX 2 DITA
     [xslt]       
     [xslt]       Version: ^version^ - build ^buildnumber^ at ^timestamp^
     [xslt]       
     [xslt]       Parameters:
     [xslt]       
     [xslt]       + styleMapUri     = "file:/C:/DITA-OT/DITA-OT1.8.5/style2tagmap.xml"
     [xslt]       + mediaDirUri     = "file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/topics/media"  
     [xslt]       + rootMapName     = "root-topic"
     [xslt]       + rootTopicName   = "root-topic"
     [xslt]       + submapNamePrefix= "map"      
     [xslt]       + rootMapUrl      = "root-topic.ditamap"
     [xslt]       + rootTopicUrl    = "root-topic.dita"
     [xslt]       + topicExtension  = ".dita"
     [xslt]       + fileNamePrefix  = ""      
     [xslt]       + filterBr        = "false"      
     [xslt]       + filterTabs      = "false"      
     [xslt]       + language        = "en-US"      
     [xslt]       + outputDir       = "file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/"  
     [xslt]       + debug           = "false"
     [xslt]       + includeWordBackPointers= "true"  
     [xslt]       + chartsAsTables  = "false"  
     [xslt]       + saveIntermediateDocs  = "false"  
     [xslt]       
     [xslt]       Global Variables:
     [xslt]       
     [xslt]       + platform         = "windows"
     [xslt]       + debugBoolean     = "false"
     [xslt]       + doSaveIntermediateDocs = "false"
     [xslt]       
     [xslt]       ==========================================
     [xslt]     
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Generating initial simple WP doc....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] wordml2simple: Processing DOCX document.xml file to generate intermediate simpleML XML...
     [xslt]  + [INFO] styleMap=file:/C:/DITA-OT/DITA-OT1.8.5/style2tagmap.xml
     [xslt]  + [INFO] Found 2 font-to-Unicode maps
     [xslt]  + [INFO]   - font2UnicodeMapSymbol.xml
     [xslt]  + [INFO]   - font2UnicodeMapWingdings.xml
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  - [WARNING] wordml2simple: Unhandled element w:trPr/w:cnfStyle
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [WARN] lookupStyleName(): No style definition found for style ID "entry", returning style ID "entry"
     [xslt]  + [INFO] wordml2simple: Intermediate simpleML document generated.
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Doing level fixup....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Doing general simpleWpDoc fixup....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Generating DITA result....
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] ++++++++++++++++++++++++++++++ 
     [xslt]  + [INFO] 
     [xslt]  + [INFO] simple2dita: Processing intermediate simpleML XML to generate DITA XML...
     [xslt]  + [INFO]    
     [xslt]  + [INFO] ++++++++++++++++++++++++++++++
     [xslt]  + [INFO] simple2dita: Phase 1: Generate DITA maps and topics as a single XML document....
     [xslt]  + [DEBUG] saving $resultDocs to 
     [xslt] file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/resultDocs.xml
     [xslt]  + [INFO] simple2dita: Fixing up xrefs in the result documents...
     [xslt]  + [DEBUG] saving $resultDocsFixedUp to 
     [xslt]         file:/C:/DITA-OT/DITA-OT1.8.5/all_defaults/dita/resultDocsFixedUp.xml
     [xslt]  + [INFO] simple2dita: Phase 2: Generate the result map and topic documents...
     [xslt]  + [INFO] simple2dita: Done processing simpleML document.
     [xslt]  + [INFO] ====================================
     [xslt]  + [INFO] Done.
     [xslt]  + [INFO] ====================================
     [echo] [INFO] Transform complete

clean.temp:

word2dita:

dita2word2dita:

start-process:

init-logger:

init-URIResolver:

use-init:

check-arg:
    [mkdir] Created dir: C:\DITA-OT\DITA-OT1.8.5\temp\temp20150708120916185
     [echo] *****************************************************************
     [echo] * basedir = C:\DITA-OT\DITA-OT1.8.5
     [echo] * dita.dir = C:\DITA-OT\DITA-OT1.8.5
     [echo] * input = C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap
     [echo] * inputdir = C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita
     [echo] * transtype = ${transtype}
     [echo] * tempdir = C:\DITA-OT\DITA-OT1.8.5\temp\temp20150708120916185
     [echo] * outputdir = C:\DITA-OT\DITA-OT1.8.5\out
     [echo] * extname = ${dita.ext}
     [echo] * clean.temp = ${clean.temp}
     [echo] * DITA-OT version = 1.8.5
     [echo] * XML parser = Xerces
     [echo] * XSLT processor = Saxon
     [echo] * collator = ICU
     [echo] *****************************************************************
     [echo] #Ant properties
     [echo] #Wed Jul 08 12:09:16 CDT 2015
     [echo] args.css.file.temp=${args.css}
     [echo] args.css.real=${args.css}
     [echo] args.grammar.cache=yes
     [echo] args.input=C\:\\DITA-OT\\DITA-OT1.8.5\\all_defaults\\dita\\word2bookmap_test_01.ditamap
     [echo] args.logdir=C\:\\DITA-OT\\DITA-OT1.8.5\\out
     [echo] args.xml.systemid.set=yes
     [echo] dita-ot-dir=C\:DITA-OTDITA-OT1.8.RC
     [echo] dita.dir=C\:\\DITA-OT\\DITA-OT1.8.5
     [echo] dita.input.dirname=C\:\\DITA-OT\\DITA-OT1.8.5\\all_defaults\\dita
     [echo] dita.input.filename=word2bookmap_test_01.ditamap
     [echo] dita.map.filename.root=word2bookmap_test_01
     [echo] dita.plugin.com.kpe.doctype.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\com.kpe.doctype
     [echo] dita.plugin.com.sophos.tocjs.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\com.sophos.tocjs
     [echo] dita.plugin.net.sourceforge.dita4publishers.doctypes.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\net.sourceforge.dita4publishers.doctypes
     [echo] dita.plugin.org.d4p.graphviz.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.graphviz
     [echo] dita.plugin.org.dita-community.adjust-copy-to.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita-community.adjust-copy-to
     [echo] dita.plugin.org.dita-community.common.xslt.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita-community.common.xslt
     [echo] dita.plugin.org.dita-community.preprocess-extensions.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita-community.preprocess-extensions
     [echo] dita.plugin.org.dita.base.dir=C\:\\DITA-OT\\DITA-OT1.8.5
     [echo] dita.plugin.org.dita.docbook.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.docbook
     [echo] dita.plugin.org.dita.eclipsecontent.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.eclipsecontent
     [echo] dita.plugin.org.dita.eclipsehelp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.eclipsehelp
     [echo] dita.plugin.org.dita.htmlhelp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.htmlhelp
     [echo] dita.plugin.org.dita.javahelp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.javahelp
     [echo] dita.plugin.org.dita.legacypdf.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\legacypdf
     [echo] dita.plugin.org.dita.odt.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.odt
     [echo] dita.plugin.org.dita.pdf.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.pdf
     [echo] dita.plugin.org.dita.pdf2.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.pdf2
     [echo] dita.plugin.org.dita.specialization.dita11.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.specialization.dita11
     [echo] dita.plugin.org.dita.specialization.dita132.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.specialization.dita132
     [echo] dita.plugin.org.dita.specialization.eclipsemap.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.specialization.eclipsemap
     [echo] dita.plugin.org.dita.specialization.h2d.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\h2d
     [echo] dita.plugin.org.dita.troff.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.troff
     [echo] dita.plugin.org.dita.wordrtf.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.wordrtf
     [echo] dita.plugin.org.dita.xhtml.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita.xhtml
     [echo] dita.plugin.org.dita4publishers.common.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.common.html
     [echo] dita.plugin.org.dita4publishers.common.mapdriven.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.common.mapdriven
     [echo] dita.plugin.org.dita4publishers.common.xslfo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.common.xslfo
     [echo] dita.plugin.org.dita4publishers.common.xslt.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.common.xslt
     [echo] dita.plugin.org.dita4publishers.dita2indesign.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.dita2indesign
     [echo] dita.plugin.org.dita4publishers.doctypes.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.doctypes
     [echo] dita.plugin.org.dita4publishers.enumeration-d.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.enumeration-d.fo
     [echo] dita.plugin.org.dita4publishers.enumeration-d.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.enumeration-d.html
     [echo] dita.plugin.org.dita4publishers.epub.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.epub
     [echo] dita.plugin.org.dita4publishers.formatting-d.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.formatting-d.fo
     [echo] dita.plugin.org.dita4publishers.formatting-d.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.formatting-d.html
     [echo] dita.plugin.org.dita4publishers.html2.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.html2
     [echo] dita.plugin.org.dita4publishers.html5.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.html5
     [echo] dita.plugin.org.dita4publishers.json.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.json
     [echo] dita.plugin.org.dita4publishers.kindle.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.kindle
     [echo] dita.plugin.org.dita4publishers.math-d.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.math-d.html
     [echo] dita.plugin.org.dita4publishers.math.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.math
     [echo] dita.plugin.org.dita4publishers.media-d.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.media-d.html
     [echo] dita.plugin.org.dita4publishers.pubContent-d.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.pubContent-d.fo
     [echo] dita.plugin.org.dita4publishers.pubmap.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.pubmap.fo
     [echo] dita.plugin.org.dita4publishers.pubmap.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.pubmap.html
     [echo] dita.plugin.org.dita4publishers.rss.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.rss
     [echo] dita.plugin.org.dita4publishers.ruby-d.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.ruby.fo
     [echo] dita.plugin.org.dita4publishers.ruby.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.ruby.html
     [echo] dita.plugin.org.dita4publishers.sample.epub_override.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.sample.epub_override
     [echo] dita.plugin.org.dita4publishers.word2dita.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.word2dita
     [echo] dita.plugin.org.dita4publishers.xmldomain.doctypes.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.xmldomain.doctypes
     [echo] dita.plugin.org.dita4publishers.xmldomain.fo.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.xmldomain.fo
     [echo] dita.plugin.org.dita4publishers.xmldomain.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.dita4publishers.xmldomain.html
     [echo] dita.plugin.org.example.d4p.epub-custom.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.example.d4p.epub-custom
     [echo] dita.plugin.org.example.d4p.html2extensions.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.example.d4p.html2extensions
     [echo] dita.plugin.org.example.d4p.word2ditaextension.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.example.d4p.word2ditaextension
     [echo] dita.plugin.org.oasis-open.dita.learning2domain.doctypes.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.oasis-open.learning2domain.doctypes
     [echo] dita.plugin.org.oasis-open.dita.mathml.doctypes.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.oasis-open.dita.mathml.doctypes
     [echo] dita.plugin.org.oasis-open.dita.mathml.html.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.oasis-open.dita.mathml.html
     [echo] dita.plugin.org.oasis-open.dita.mathml.test.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins\\org.oasis-open.dita.mathml.test
     [echo] dita.plugins.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\plugins
     [echo] dita.preprocess.reloadstylesheet=false
     [echo] dita.temp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\temp\\temp20150708120916185
     [echo] dita.topic.filename.root=word2bookmap_test_01.ditamap
     [echo] dita2wordToDita.buildfile.dir=C\:\\DITA-OT\\DITA-OT1.8.5
     [echo] ditaot.dir=C\:\\
     [echo] ditaot.temp.dir=C\:\\DITA-OT\\DITA-OT1.8.5\\temp
     [echo] *****************************************************************

output-css-warn-message:

output-msg:

build-init:

gen-list:
 [gen-list] GenMapAndTopicListModule.execute(): Starting...
 [gen-list] Using Xerces grammar pool for DTD and schema caching.
 [gen-list] Processing C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap
 [gen-list] GenMapAndTopicListModule.execute(): Execution time: 260 milliseconds

BUILD FAILED
C:\DITA-OT\DITA-OT1.8.5\dita-ot-run-word2dita.xml:39: The following error occurred while executing this line:
C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita.base\build_preprocess.xml:24: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap'. The XML parser reported the following error: : word2bookmap_test_01.ditamap Line 1:cvc-elt.1.a: Cannot find the declaration of element 'p'.


Total time: 3 seconds
```

**Comment by drmacro** [comment]
The word-to-DITA transform worked (or at least didn't fail).

The failure is in the parsing of the generated file:

````
C:\DITA-OT\DITA-OT1.8.5\plugins\org.dita.base\build_preprocess.xml:24: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'C:\DITA-OT\DITA-OT1.8.5\all_defaults\dita\word2bookmap_test_01.ditamap'. The XML parser reported the following error: : word2bookmap_test_01.ditamap Line 1:cvc-elt.1.a: Cannot find the declaration of element 'p'.
````

So look at the generated XML and see what the issue is. Could be as simple as not specifying a good DTD for the output file.

**Comment by peytonwashere** [comment]
I checked out the XML and I'm only getting the .ditamap, not any broken-out topics. The ditamap looks like this:

``` 
<?xml version="1.0" encoding="UTF-8"?><p>[Word Style: Normal] There can be body copy under the topic title. </p><title>Section Title [Word Style: Section Title (h4)]</title><p>[Word Style: Normal] Sections typically have plenty of body copy. And will trigger a page break in the LMS output. The LMS page will include all of the content after the Section Title, until a new Section Title is added or a manual page break is indicated.  </p><dt>Sub-section Title [Word Style: Sub-section Title (h5)]</dt><dd>[Word Style: Sub-section Text] Sub-sections are fairly common in content and will stay with their parent Section on the LMS, unless manual page breaks are indicated. </dd><dt>Sub-sub-section Title [Word Style: Sub-sub-section Title (h6)]</dt><dd>[Word Style: Normal] Sub-sub-sections are less common, but accounted for in this template.  Again, these will stay with their parent Sub-section.</dd><label>[Word Style: Example Title] Example:</label><p>[Word Style: Example] This style can be used for the following kinds of content. Note that the title of this content can vary.  See below for variants used as a title for this type of structure:</p><li>[Word Style: Example Bullet] For Example</li><li>Sample</li><li>Take Note</li><li>And the list goes on…</li><p>[Word Style: Normal] Body copy can continue after an Example.  The author may have to select “Normal” from the Word Styles Gallery to set the font back to the correct format to be converted as body copy.</p><p>[Word Style: Normal] You can also use a variety of lists.</p><li>[Word Style: Bullets]Item 1</li><li>Item 2</li><li>Item 3</li><li>[Word Style: Bullets 2] Item 3 sub item 1</li><li>Sub item 2</li><li>[Word Style: Numbered List] Item 1</li><li>Item 2</li><li>Item 3</li><li>[Word Style: Numbered List 2] Sub item a</li><li>Sub item b</li><p>[Word Style: Normal]: You can also have a combination of list styles.</p><li>[Word Style: Numbered List] Item 1</li><li>Item 2</li><li>[Word Style: Bullets 2] Sub bullet 1</li><li>Sub bullet 2 </li><p>[Word Style: Task Text] Insert Activity: sample_Flash.swf </p><p>[Word Style: Task Text] Size: 800x530</p><p id="p__GoBack">[Word Style: Task Text] Activities are a task, so they need to be handled by the transforms a bit differently.  Because of this, be sure to include "Insert Activity:" before supplying the swf file name. We may use this to trigger some tagging on conversion.  Also, include the width and height measurements of the swf for production purposes. </p>
```
So, my text is coming through but none of the bookmap elements are there. I retried this with a file that I had been using with the older version of the plugin (and with the style2tagmap.xml that has been working) and this is still happening. Not sure where the problem is lying, but essentially the same thing happened when I ran the provided word2bookmap_test_01.docx and style2tagmap.xml. 

It definitely feels like I'm getting closer! Thanks for your help!

**Comment by drmacro** [comment]
If you're using your own style-to-tag map you have to migrate it to the new style-to-tag map markup. Use the org.dita4publishers.word2dita/utils/style2tagmapMigrator.xsl transform. You just give it your style-to-tag map as input and it will produce the migrated version. The migrated version should just work.

**Comment by drmacro** [comment]
Closing due to age. If this is still a problem please open a new issue.

**Comment by pavandg2006** [comment]
Hi, I am facing the same issue with the latest code.

Here is the error:

C:\Users\pavand\word2dita\all_defaults\word>ant -f dita-ot-run-word2dita.xml
Buildfile: C:\Users\pavand\word2dita\all_defaults\word\dita-ot-run-word2dita.xml

transformMyDoc:
Duplicated project name in import. Project dita2html5 defined first in C:\dita-ot-3.3.1\plugins\org.dita.html5\build_dita2html5.xml and again in C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.html5\build_transtype-html5.xml

d4p.wordToDita.init:

wordToDita:
     [echo] [DEBUG] wordToDita.dir=C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita

BUILD FAILED
C:\Users\pavand\word2dita\all_defaults\word\dita-ot-run-word2dita.xml:24: The following error occurred while executing this line:
C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
Error reading project file C:\Users\pavand\word2dita\all_defaults\word\build-word2dita.xml: C:\Users\pavand\word2dita\all_defaults\word\build-word2dita.xml

Total time: 0 seconds

Can you please have a look.

**Comment by pavandg2006** [comment]
Actually, I changed the DITA OT path in the dita-ot-run-word2dita.xml to point to my DITA OT and re-run.

Got the following error. 

C:\Users\pavand\word2dita\all_defaults\word>ant -f dita-ot-run-word2dita.xml
Buildfile: C:\Users\pavand\word2dita\all_defaults\word\dita-ot-run-word2dita.xml

transformMyDoc:
Duplicated project name in import. Project dita2html5 defined first in C:\dita-ot-3.3.1\plugins\org.dita.html5\build_dita2html5.xml and again in C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.html5\build_transtype-html5.xml

d4p.wordToDita.init:

wordToDita:
     [echo] [DEBUG] wordToDita.dir=C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita

checkWordDoc:

checkParameters:

initProperties:
     [echo] +++ word2dita-specific properties:
     [echo] #Ant properties
     [echo] #Thu Apr 18 13:24:04 IST 2019
     [echo] w2d.base.dir=C\:\\dita-ot-3.3.1\\plugins\\net.sourceforge.dita4publishers.word2dita
     [echo] w2d.clean.output.dir=true
     [echo] w2d.debug.xslt=true
     [echo] w2d.defaultStyleToTagMap=C\:\\dita-ot-3.3.1\\plugins\\net.sourceforge.dita4publishers.word2dita\\xsl\\word-builtin-styles-style2tagmap.xml
     [echo] w2d.generate.navtitles=true
     [echo] w2d.have.word.doc=true
     [echo] w2d.language=en-US
     [echo] w2d.out.dir=C\:\\Users\\pavand\\word2dita\\all_defaults\\dita
     [echo] w2d.root.map.name=word2bookmap_test_01
     [echo] w2d.root.output.filename=word2bookmap_test_01.ditamap
     [echo] w2d.style-to-tag-map=C\:\\Users\\pavand\\word2dita\\all_defaults\\word\\style2tagmap.xml
     [echo] w2d.temp.dir=C\:\\Users\\pavand\\word2dita\\all_defaults\\word\\${dita.temp.dir}
     [echo] w2d.topic.extension=.dita
     [echo] w2d.word2dita.xslt=C\:\\dita-ot-3.3.1\\plugins\\net.sourceforge.dita4publishers.word2dita\\xsl\\docx2dita.xsl
     [echo] w2p.do.clean.output.dir=true

doWord2Dita:

unzipWordDoc:
    [unzip] Expanding: C:\Users\pavand\word2dita\all_defaults\word\word2bookmap_test_01.docx into C:\Users\pavand\word2dita\all_defaults\word\${dita.temp.dir}\word2bookmap_test_01
     [echo] w2d.style-to-tag-map='C:\Users\pavand\word2dita\all_defaults\word\style2tagmap.xml'

cleanOutputDir:
     [echo] [INFO] Cleaning output directory C:\Users\pavand\word2dita\all_defaults\dita...

transformWordToDita:
     [echo] [INFO] Creating output directory C:\Users\pavand\word2dita\all_defaults\dita...
     [echo] [INFO] Creating output file word2bookmap_test_01.ditamap...
     [echo] [INFO] Generating DITA documents from Word document in output directory C:\Users\pavand\word2dita\all_defaults\dita...
     [echo] [INFO]   Using XSLT C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita\xsl\docx2dita.xsl...

BUILD FAILED
C:\Users\pavand\word2dita\all_defaults\word\dita-ot-run-word2dita.xml:24: The following error occurred while executing this line:
C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita\build_transtype-word2dita.xml:28: The following error occurred while executing this line:
C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita\build-word2dita.xml:157: The following error occurred while executing this line:
C:\dita-ot-3.3.1\plugins\net.sourceforge.dita4publishers.word2dita\build-word2dita.xml:201: Reference dita.catalog not found.

Total time: 0 seconds

**Comment by drmacro** [comment]
You must be using an old version because this: 

net.sourceforge.dita4publishers.word2dita

Is not the name of the plugin any more.

The latest release is here:

https://github.com/dita4publishers/org.dita4publishers.word2dita/tree/1.0.0RC27
